baseurl      = "fossrd.github.io"
title        = "FOSSRD BLOG"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Tu blog de Open Source, SRE y IT!"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Blog sobre Open Source, SRE y IT de la comuinidad fossrd en telegram tt.me/fossrd"
  keywords = "homepage, blog, SRE, IT, Open Source, Fossrd, Telegram"
  images = ["/img/fossrd.png"]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "FOSSRD's BLOG"
    subtitle = "Simple blog about Open Source, SRE and IT"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otros artículos"

    [languages.en.params.logo]
    #  logoText = "FOSS RD"
      logoHomeLink = "/"
    # or
    #
      path = "/img/fossrd.png"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"   
